#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
mkdir $OPENSHIFT_DATA_DIR/media
fi

if [ ! -d $OPENSHIFT_REPO_DIR/wsgi/static/collected_static ]; then
mkdir $OPENSHIFT_REPO_DIR/wsgi/static/collected_static
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
export PYTHONPATH="${OPENSHIFT_REPO_DIR}:${OPENSHIFT_REPO_DIR}mediathread:${OPENSHIFT_REPO_DIR}mediathread/mediathread"

cd ${OPENSHIFT_REPO_DIR}mediathread
pip install -r ${OPENSHIFT_REPO_DIR}requirements.openshift.txt --log /tmp/pip.log --build /tmp/build
