#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
source ${OPENSHIFT_REPO_DIR}secret_keys
 
export PYTHON_EGG_CACHE=${OPENSHIFT_PYTHON_DIR}virtenv/lib/python-2.6/site-packages
export PYTHONPATH="${OPENSHIFT_REPO_DIR}:${OPENSHIFT_REPO_DIR}mediathread:${OPENSHIFT_REPO_DIR}mediathread/mediathread"

export DJANGO_SETTINGS_MODULE=settings_openshift

echo "Executing 'django-admin.py syncdb --noinput'"
django-admin.py syncdb --noinput --settings=$DJANGO_SETTINGS_MODULE

echo "Executing 'django-admin.py migrate'"
django-admin.py migrate --settings=$DJANGO_SETTINGS_MODULE

#cp ${OPENSHIFT_REPO_DIR}sherdjs-0.1.0.tar.gz ${OPENSHIFT_REPO_DIR}mediathread/media/js/
#cd ${OPENSHIFT_REPO_DIR}mediathread/media/js/
#tar xvzf sherdjs-0.1.0.tar.gz

cd ${OPENSHIFT_REPO_DIR}mediathread
echo "Executing 'django-admin.py collectstatic'"
django-admin.py collectstatic --noinput --settings=$DJANGO_SETTINGS_MODULE
#django-admin.py compress --settings=$DJANGO_SETTINGS_MODULE

cp ${OPENSHIFT_REPO_DIR}mediathread/crossdomain.xml ${OPENSHIFT_REPO_DIR}wsgi/static/collected_static

#echo "Executing 'python ${OPENSHIFT_REPO_DIR}mediathread/manage.py collectstatic --noinput -v0'"
#python "$OPENSHIFT_REPO_DIR"mediathread/manage.py collectstatic --noinput -v0 --settings=$DJANGO_SETTINGS
